import json
import logging
from app.core.llm_agent import llm
from app.features.RAG.knowledge_base import retrieve_clinical_context

logger = logging.getLogger(__name__)

async def generate_patient_insights(patient_data: dict) -> dict:
    """
    RAG Orchestration Service.
    1. Retrieve Context based on the specific patient's risk profile.
    2. Build Augmented Prompts.
    3. Query the Groq Core Agent and return JSON insights.
    """
    # 1. Retrieval
    context_list = retrieve_clinical_context(patient_data)
    context_string = "\n".join(context_list)
    
    logger.info(f"Retrieved {len(context_list)} context chunks for patient.")

    # 2. Augmented Prompt Engineering
    system_prompt = f"""You are the CareFlow AI Clinical Decision Support Engine.
You are assisting a physician by analyzing a patient's Non-Communicable Disease (NCD) Risk output generated by an XGBoost model.

## RETRIEVED MEDICAL CONTEXT (USE THIS FACTUALLY):
--- 
{context_string}
---

Your job is to analyze the patient data objectively using *only* the retrieved context and standard medical knowledge.
Break down why the patient's risk is what it is, and provide actionable Clinical Guidelines explicitly based on the text above if applicable.

You MUST respond strictly in a valid JSON format with the following keys exactly:
{{
    "analysis_summary": "Short 2 sentence overview of their overall risk state.",
    "primary_risk_factors": ["Factor 1", "Factor 2"],
    "clinical_guidelines": ["Guideline 1", "Guideline 2"],
    "recommended_action": "Patient should immediately..."
}}
"""

    user_query = patient_data.get('user_query')

    user_prompt = f"""Please analyze the following patient profile.
    
Patient Data:
{json.dumps(patient_data, indent=2)}
"""

    if user_query:
        user_prompt += f"\n\nThe user specifically asked you (copilot context): '{user_query}'\nPlease tailor your analysis to directly answer this question while strictly following the JSON response structure."

    user_prompt += "\nRemember to only output the valid JSON format."

    # 3. Call Core LLM Agent
    try:
        # temperature=0.1 to keep clinical outputs deterministic and accurate
        result_json = llm.generate_json(system_prompt=system_prompt, user_prompt=user_prompt, temperature=0.1)
        return result_json
        
    except Exception as e:
        logger.error(f"RAG Service Error: {str(e)}")
        # Provide graceful degradation fallback
        return {
            "analysis_summary": "Error generating insights due to LLM failure.",
            "primary_risk_factors": ["System Error"],
            "clinical_guidelines": ["Consult primary physician offline."],
            "recommended_action": "System unavailable."
        }
